# Use dedicated Ansible task for personal infra (jeanmarc.lacroix@free.fr)
- hosts: image
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: 1/3 disable Apparmor in order to correct LXC startup 
      shell: |
        sed  \
          -i \
          's/ifnames=0/ifnames=0 apparmor=0 cgroup_enable=memory loglevel=7/g' \
          /etc/default/flash-kernel \
        && \
        flash-kernel

    - name: 2/3 Install python and openssh-server as defined in Debian standard Buster
      shell: |
        apt-get install -y python openssh-server

    - name: 3/3 Install public ssh key into root account
      shell: |
        mkdir -p /root/.ssh \
          && \
        echo \
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICqkpxBMUFMFqu7vgPCb9ys4HGHP1aobyQDJQ37yFwbR -- ssh-key for ansible@solo samedi 14 décembre 2019, 08:13:33 (UTC+0100) br-ansible.2.7.5-debian-stretch-9.11-dns-android 33cc980c87863820dfa6e23ed24e83a65ad459e4  --" \
          > /root/.ssh/authorized_keys



