name: Build images matrix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh_actions ]
#  schedule:
#    - cron:  '42 0 * * *'
  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buster_armhf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        armhf_boards: [cubieboard2, cubietruck, cubietruck-plus, orangepi-r1, nanopi-r1, odroid-hc1, udoo-quad, jetson-tk1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Install needed packagest
      run: |
        sudo apt-get update
        sudo apt-get install python3-cliapp cmdtest debootstrap qemu-utils kpartx qemu-user-static binfmt-support zerofree lbzip2 ansible

    - name: Install vmdb2
      run: |
        wget http://ftp.de.debian.org/debian/pool/main/v/vmdb2/vmdb2_0.22-1_all.deb
        sudo dpkg -i vmdb2_0.22-1_all.deb

    - name: Build buster armhf board
      uses: ./.github/actions/build-board
      with:
        board_name: '${{ matrix.armhf_boards }}'
        deb_version: 'buster'
        architecture: 'armhf'

  buster_arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arm64_boards: [rock64, pine-a64-plus, pinebook, nanopi-neo2, odroid-n2, jetson-tx1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a set of commands using the runners shell
    - name: Install needed packagest
      run: |
        sudo apt-get update
        sudo apt-get install python3-cliapp cmdtest debootstrap qemu-utils kpartx qemu-user-static binfmt-support zerofree lbzip2 ansible

    - name: Install vmdb2
      run: |
        wget http://ftp.de.debian.org/debian/pool/main/v/vmdb2/vmdb2_0.22-1_all.deb
        sudo dpkg -i vmdb2_0.22-1_all.deb

    - name: Build buster arm64 board
      uses: ./.github/actions/build-board
      with:
        board_name: '${{ matrix.arm64_boards }}'
        deb_version: 'buster'
        architecture: 'arm64'

